spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/switchmiddlewaredb
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
jwt:
  secret: c999hhf98gfbn9iijd903939nbenn3i38bbdieippi3
